### ISSUE TITLE
[Feature request] Kernel configuration

### ISSUE THREAD

**Issue by keiosweb** [octobercms/library#106]
Laravel 5 architecture depends on application using it's own Kernel class, which has array fields used for configuration - global and route-related middleware stacks. Currently October allows no access to edit those configurations and uses hard-coded kernel class October\Rain\Foundation\Http\Kernel.

My proposition is to allow October's kernel class to import settings the same way service providers are registered - via config file. This would allow to have separate middleware stacks for different environments and what is most important, allow developers to add their own middlewares to their apps.

**Comment by daftspunk** [comment]
This is overcome by creating an *app/* directory and following the L5 application structure. The Kernel classes should inherit the October\Rain\Foundation classes to ensure smooth operation.

I will see what can be done about plugins registering Middleware as part of the routing process.

**Comment by daftspunk** [comment]
Plugins can now register Middleware by including a file **init.php**, similar to **routes.php**, with the following code:

```
Backend\Classes\BackendController::extend(function($controller) {
    $controller->middleware('Namespace\Path\To\Middleware');
});

Cms\Classes\CmsController::extend(function($controller) {
    $controller->middleware('Namespace\Path\To\Middleware');
});
```

**Comment by keiosweb** [comment]
nice :+1:

**Comment by goslund** [comment]
Hello. I've been trying to start writing a set of plugins to manage my business, and I need to be able to do tokens, and all the jazz. I'm stumbling on adding some middleware to my application's route. @daftspunk says init.php, which does work as expected. The problem I'm facing is that I need to protect some custom routes that I have made inside of routes.php. 
Editing init.php does not affect the routes from the routes.php file. Is there some way to use my middleware with those routes? 
Thanks,
Geoff
