### ISSUE TITLE
Unterminated comment starting line

### ISSUE THREAD

**Issue by vojtasvoboda** [octobercms/library#110]
When I use comments in my migration file, e.g.:

```
/** Objects FK */
$table->integer('object_id')->unsigned()->nullable();
$table->foreign('object_id')->references('id')->on('my_objects');
```
it sometimes throw warning:

```
PHP Warning:  Unterminated comment starting line 20 in .../vendor/october/rain/src/Database/Updater.php on line 103
```

When I dump() [$buffer](https://github.com/octobercms/library/blob/master/src/Database/Updater.php#L102), it prints:

```
/** Project FK */
$table->integer('project_id')->default(1);

/** Obje"""
PHP Warning:  Unterminated comment starting line 20 in .../vendor/october/rain/src/Database/Updater.php on line 105
```

I think that in the middle of word 'Object' ends 512B buffer, but don't know how to solve it.

**Comment by daftspunk** [comment]
I haven't found this to be an issue, the migration is processed by Laravel so perhaps the Laravel folks may be able to shed some more light on this.

**Comment by vojtasvoboda** [comment]
Yes, but this warning comes from this line:

[https://github.com/octobercms/library/blob/master/src/Database/Updater.php#L103](https://github.com/octobercms/library/blob/master/src/Database/Updater.php#L103)

where is native token_get_all() function. It could be issue with reading migration and seeding files from version.yaml and spliting it to 512B tokens, because if you split comment line in the middle, it throws warning.

I found it can be PHP bug with parsing inline comments:

[http://php.net/manual/en/function.token-get-all.php#92653](http://php.net/manual/en/function.token-get-all.php#92653) - second point

Maybe removing comments before parsing would fix this warning, or maybe [php_check_syntax()](http://php.net/manual/en/function.php-check-syntax.php#77318).

**Comment by frijj2k** [comment]
Yup it's a bug...  Comments like this:    /* ... */     cause it when contained within a migration file.  If I remove that style of comment and replace with a double forward slash on each line, the warning goes away.
