### ISSUE TITLE
Localize the exceptions

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/library#132]
Is it an idea to localize the exceptions given by the Rain library?

For example the login errors like: 

                // Incorrect password
                if ($credential == 'password') {
                    throw new AuthException(sprintf('A user was found to match all plain text credentials however hashed credential "%s" did not match.', $credential));
                }

I understand the library acts like a kind of framework and should work standalone, however maybe its an idea to defer the exception by returning the exception type and then localize it in octobercms?

Let me know what you think.

P.S. It's for about 50 messages/exceptions

**Comment by mahony0** [comment]
Thumb up for this.. This is core but needs to translate for usability on front-end

**Comment by daftspunk** [comment]
Look at how Halcyon implements Exceptions:

https://github.com/octobercms/library/tree/develop/src/Halcyon/Exception

And then how those custom Exceptions are localized in the platform space:

https://github.com/octobercms/october/blob/f68eb3f20f00fa2ee81876d4c560feafe34ebbf2/modules/cms/classes/CmsObject.php#L279-L321

It is important that the library is not tainted by the platform.

**Comment by robinbonnes** [comment]
So can we do this in the same way as with Halcyon?

**Comment by daftspunk** [comment]
Yes that's right. If this is still an issue, please log it in the main October repo.
