### ISSUE TITLE
use Extension in my code

### ISSUE THREAD

**Issue by mohamedsharaf** [octobercms/library#180]
i saw a post on sitepoint  where i can extend user class methods from plugin i ke the concept 
i need to use it on my own code not the whole framework

class Plugin extends PluginBase
{
    public function boot()
    {
        User::extend(function($model){
            $model->belongsTo['team'] = ['Rafie\SitepointDemo\Models\Team'];
        });
    }
}

how can i make my laravel user class like this but dont need to use class inheritance 
i see it can be done buy traits but not cleared in documentation

n some cases you may not wish to extend the `ExtensionBase` or `Extendable` classes, due to other needs. So you can use the traits instead, although obviously the behavior methods will not be available to the parent class.

- When using the `ExtensionTrait` the methods from `ExtensionBase` should be applied to the class.

- When using the `ExtendableTrait` the methods from `Extendable` should be applied to the class.

any idea how i can do it

**Comment by daftspunk** [comment]
Maybe this is one for the Laravel community. October has several
enhancements that makes this possible. Perhaps it would be easier just to
use the October database package.

**Comment by mohamedsharaf** [comment]
after some tries i made it but the problem when i add dynamic method for elequent say "roles()"

$user->roles() works fine
but elequent user->roles not work

any idea

**Comment by daftspunk** [comment]
If this is still an issue, please log it in the main October repo.
