### ISSUE TITLE
HtmlBuilder::limit fails with umlauts

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/library#184]
When passing a string to HtmlBuilder::limit that includes umlauts, the string encoding somehow gets messed up. The following test case fails: https://github.com/OFFLINE-GmbH/library/commit/dbaff8e164f5b081e03b72e1e12c4b9f4c72cb36

```php
public function testLimitEncoding()
{
    $result = with(new HtmlBuilder)->limit('<p>Er hörte leise Schritte hinter sich. Das bedeutete nichts Gutes.</p>', 10);
    $this->assertEquals('<p>Er hörte l...</p>', $result);
}
```

Expected output is 
```
<p>Er hörte l...</p>
```
Received output is

```
<p>Er hö�te l...</p>
```

**Comment by daftspunk** [comment]
If this is still an issue, please log it in the main October repo. Also consider submitting a Pull Request to fix it, most of our multi lingual features stem from the community.
