### ISSUE TITLE
Add encrypted attribute modifier

### ISSUE THREAD

**Issue by daftspunk** [octobercms/library#3]
Related issue:
https://github.com/rainlab/mailchimp-plugin/issues/1

In the same family as hashable, purgeable and jsonable; another type is needed for storing sensitive data in the database `encrypted`.

This should be added to October's ActiveRecord model. 

```php
class User extends \October\Rain\Database\Model
{
    protected $hashable = ['password'];

    protected $purgeable = ['password_confirmation'];

    protected $jsonable = ['permissions'];

    protected $encrypted = ['api_key']; // <== New
}
```

* **$encrypted** - values are encrypted and decrypted for storing sensitive data.

**Comment by vojtasvoboda** [comment]
+1

**Comment by vojtasvoboda** [comment]
Validation doesn't work with Encryptable trait. It validate every field after encryption. For example I have field name with rule 'between:3,35', but after encryption name is something like that:

'eyJpdiI6IlRZeUZWQ25JU3JCelZEUjVuXC9rV3RRPT0iLCJ2YWx1ZSI6Ik9iK24rajFvZUh6QVhLZ1RLRWpGeFE9PSIsIm1hYyI6ImE5ODhmY2E3YTA1NGZjNDNhN2VlYjA5YmQxNGQxMjY1NzUzMzYxZGUwZjg0NDQ5YjljYzUzYjJjNjkzOTk2MGQifQ=='

That is for sure longer then 35 chars.

**Comment by daftspunk** [comment]
This is implemented with the Encryptable trait
