### ISSUE TITLE
Error in Filesystem class

### ISSUE THREAD

**Issue by gpasztor87** [octobercms/library#60]
Hi!

I have the following error:
Declaration of October\Rain\Filesystem\Filesystem::put() should be compatible with Illuminate\Filesystem\Filesystem::put($path, $contents, $lock = false)

**Comment by dimti** [comment]
This commit initiate that problem https://github.com/laravel/framework/commit/4e7cf5438629c82d99b921f47ff1f6c05a8d1869

I try to update laravel/framework to concrete commit dev-master#75e1c61c5d59ac6801b0e3676036f6cbb18ffc11 in composer.json of october system. But result is not fine. I unable to start system after packages update.. Some laravel commits have problem with Foundation/helpers.php file. After update to commit 75e1c61 of laravel, a have problem with "Class 'Patchwork\\Utf8\\Bootup' not found"

What is class Patchwork\\Utf8\\Bootup and can i find it? where package contains this class?

composer update - that really dangerous operation...

**Comment by dimti** [comment]
Oh.

Bad idea use laravel/framework from branch master..

october/rain worked normally with laravel/framework 4.2.16 https://github.com/laravel/framework/tree/v4.2.16

**Comment by daftspunk** [comment]
What version causes this breakage? We currently use `"laravel/framework": "4.2.*",`

I just performed a composer update and it seems fine.

**Comment by gpasztor87** [comment]
I tried now again with 4.2.* but it's not working. I have the same error. 
Now I use 4.2.16 and it's fine.
