### ISSUE TITLE
Throttling by delay instead of IP

### ISSUE THREAD

**Issue by andrew13** [octobercms/library#8]
I'm willing to implement throttling by delay instead of IP.

Currently it is by IP which is fairly easy to fake.
https://github.com/octobercms/library/blob/master/src/Auth/Manager.php#L192

I would suggest that instead a delay be used.
http://blog.codinghorror.com/dictionary-attacks-101/

If desired, I'll code it up in a pull request.

**Comment by Flynsarmy** [comment]
This would be a great addition and I agree, better than IP.

**Comment by daftspunk** [comment]
I think when we discussed this a while ago, it wasn't required because when the account is suspended, it becomes suspended for everyone.

**Comment by Flynsarmy** [comment]
Couldn't I enter some other guys username/email a few times and get them locked out with no way for you to stop Mr?
